version: '3.8'

services:
  postgres:
    image: 'postgres:15.4-alpine'
    container_name: numeroscope-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: ${IMAGE_NAME}
    container_name: numeroscope-app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      NUMERO_BOT_USERNAME: ${NUMERO_BOT_USERNAME}
      NUMERO_BOT_TOKEN: ${NUMERO_BOT_TOKEN}
      NUMERO_BOT_PAYMENT_TOKEN: ${NUMERO_BOT_PAYMENT_TOKEN}
    depends_on:
      - postgres

volumes:
  postgres_data:
