spring:
  application:
    name: numeroscope
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
telegram:
  bot:
    numeroscope:
      bot-username: ${NUMERO_BOT_USERNAME}
      bot-token: ${NUMERO_BOT_TOKEN}
      bot-payment-token: ${NUMERO_BOT_PAYMENT_TOKEN}
server:
  port: ${SERVER_PORT}
logging:
  level:
    root: INFO
    org.telegram.abilitybots: DEBUG
